import React, { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styled from '@emotion/styled';

interface List {
  id: number;
}

const Home: NextPage = () => {
  const [value, setValue] = useState<string>('');
  const [list, setList] = useState<List>({} as List);
  const changeHandler = (e: React.ChangeEvent<HTMLInputElement>) => {
    console.log('change', e.target.value);
    setValue(e.target.value);
  };

  const clickHandler = () => {
    console.log('click');
    setList({ id: Math.random() * 100 });
  };

  return (
    <div>
      <Head>
        <title>Kwan-ToDoList</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container>
        todo list here
        <input onChange={changeHandler} />
        <button onClick={clickHandler}>Add</button>
      </Container>
    </div>
  );
};

export default Home;

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
`;
